language: node_js
node_js:
- '7'
before_script:
- npm install -g @angular/cli
notifications:
  slack:
    secure: GBlb/v8Y8PjSpbGycmluk8pDjMK7sNnPUThm0zNo69u3pTDVwVoaNHJN6PU4gbV+EbnnOD59QSgu0bITV7CQ4e9m7oyroXYTKM32Aw8nNOgJGndCsMNY+NTBcnHc9OlLd5wz5mLg9V/rB8zKwYM2GWYyT7XiTUIhMUxAkIX6YLaB91+iv4rqqtrWfQejdJRZHukQCM0crHTLCkyXsFT9cQMRKJ0utZ2URpefFWeLVQc5C0ycYBaLaBwoqX++QLR6yCXouQSmjlg0C93TvJPaf1Nv5pfq91Wzkew1DsbZEwmMa5sBvLpvf3W/qRDzDL8Iwj0jgCGQHFG/5yS2WJSECoeLzaLVNeoPm+kjqOzRSy+UArbJOPlyV0Ushmi0aVmr+SnPe7KMF5QyXW/NAN7F42+cVCjLRIBztKrQPW33FM88ofdgVFe9aaZSKcLV0VXDgTloDnoLkEkZEySW47vT2A511cbxznDm6NRzyhi20hDrtLj+6+v/EycTQevSaAE6VXmVow51a/tTZW1g9Jp6mDi5DRajtK2f764Dw1zhkHUtFM9vxCPL6EXhFnmGlfragzfEisPKoxNRSZU0tM4e0eOwAgsKOIaeIV39fMtEN8fVRFYmWm3JBhyvZY6y0Il1iX3W1mCt7pL6hzijrotguHAt8fERL6SAlnggO9bTH1A=
