language: node_js
node_js:
- '7'
before_script:
- npm install -g @angular/cli
notifications:
  slack:
    secure: hYrkE9d+dYiAOoccTA2vzAc5lG26zvhL89F4F2h+L/o0dx5877GtZAhcrSL/svFw6NFDQJbfpE4ZLolByn1t22WBD3pV3lNKLAJ8sFhviNxGtvk3mNQWJrXbygEGbmZSikEbpesOsl/OOkbDjpshHjDKUKb4V/S9086HhirMqAlrwN4EYS8sl1zblHd0NAVPIAdLf61keaIiF9H1GWHNuHEoLRD2k2edAlfgNlQFYsZKwOJ8tpWPhPb3dzZlhq91dqKuPLzMIWVPOTE0WbybMc5SRc97A15YFe1MOeZsZzIiSM2fIcgd0F7YMbL5eLazb1+E40fi1rMYI3WC9KsGyN4kw16yfWCO9DkykHaivBSSA+H5MEMuv+oYexcNyfQbS5rODQr51XA7BN4BVlZmOJB/2oM4THeqCV4s4x473znsYanMRPOvExZM9s6HGYyiFmqjNoPTfv2Sm58fHMhgScT8TsMiQHRgZQc3rQ4sqEM76LknsIYbXbtaQqhVbtBrYR4gra2VtajrNbXpgCRoAfF09hiAkxrtqlXgV2ksrmtBvDSdGOfEVy/08UyF8/c1tvpvRWIDqnJGTG8S9Yz8t08IeTEmiiByUlP5JXxajLTvj5a7Cn7lFVCF6Og2SUXt9Zo/f0sd3knl9aC2qPWppf285EBTuk4O+TpgCutPAOo=
